version: '3.8'

services:
  cube:
    image: cubejs/cube
    ports:
      - "4000:4000"
    restart: on-failure
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_HOST=database
      - CUBEJS_DB_NAME=cube
      - CUBEJS_DB_USER=root
      - CUBEJS_DB_PASS=root
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_API_SECRET=secret
    #volumes:
    #  - .:/cube/conf
  database:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cube_db
    ports: 
      - "3307:3306"

