version: '3.8'

services:
  cube:
    image: cubejs/cube
    ports:
      - "4001:4000"
    restart: on-failure
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_HOST=database
      - CUBEJS_DB_NAME=cube_db
      - CUBEJS_DB_USER=root
      - CUBEJS_DB_PASS=root
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_API_SECRET=secret
    volumes:
      - .:/cube/conf
  database:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cube_db
      - LANG=C.UTF-8
    ports: 
      - "3307:3306"

